language: node_js

cache: yarn

node_js:
- node
- 8
install: yarn
script:
- (cd packages/noderize-scripts && yarn remote build)
- (cd packages/create-noderize && yarn test)

jobs:
  include:
    # Deploy site
    - stage: deploy
      env: DEPLOY=website
      if: tag IS present OR branch = master
      install: (cd docs/website && yarn)
      script: skip
      before_deploy:
        # Set Git info
        - git config --global user.email "36317094+Noderize-bot@users.noreply.github.com"
        - git config --global user.name "Noderize Bot"
        - echo "machine github.com login Noderize-bot password $GITHUB_TOKEN" > ~/.netrc
      deploy:
        provider: script
        skip_cleanup: true
        script: (cd docs/website && GIT_USER=Noderize-bot yarn publish-gh-pages)
        on:
          all_branches: true
    - stage: deploy
      env: DEPLOY=npm
      if: tag IS present
      script: skip
      before_deploy:
        # Publish using $NPM_TOKEN
        - npm i -g ci-publish
      deploy:
        provider: script
        skip_cleanup: true
        script: (cd packages/noderize-scripts && ci-publish) && (cd packages/create-noderize && ci-publish)
        on:
          tags: true