language: node_js
node_js: node
cache: yarn

deploy:
  provider: script
  on:
    branch: master
  script:
    - git config --global user.email "36317094+Noderize-bot@users.noreply.github.com"
    - git config --global user.name "Noderize Bot"
    - echo "machine github.com login $GIT_USER password $GITHUB_TOKEN" > ~/.netrc
    - cd docs/website && npm install && npm run publish-gh-pages
