language: node_js
node_js: node
cache: yarn

script: skip
install: skip

jobs:
  include:
    - stage: deploy
      env: DEPLOY=website
      install: (cd docs/website && yarn)
      before_deploy:
        # Set Git info
        - git config --global user.email "36317094+Noderize-bot@users.noreply.github.com"
        - git config --global user.name "Noderize Bot"
        - echo "machine github.com login Noderize-bot password $GITHUB_TOKEN" > ~/.netrc
      deploy:
        provider: script
        skip_cleanup: true
        script: (cd docs/website && yarn publish-gh-pages)
    - stage: deploy
      env: DEPLOY=npm
      if: tag IS present
      install: yarn
      script:
        - (cd packages/create-noderize && yarn build --env production)
      before_deploy:
        # Publish using $NPM_TOKEN
        - npm i -g ci-publish
      deploy:
        provider: script
        skip_cleanup: true
        script: (cd packages/create-noderize && ci-publish) && (cd packages/noderize-scripts && ci-publish)
        on:
          tags: true