language: node_js
node_js:
- node
- stable
cache: yarn

script:
- (cd packages/scripts && yarn prepack && yarn test)
- (cd packages/create && yarn build && yarn test)

stages:
- test
- name: deploy
  if: repo = Cretezy/Noderize AND tag IS present # only deploy on tags

jobs:
  include:
  # Deploy site always
  - stage: deploy
    env: DEPLOY=website
    install: skip
    script: skip
    before_deploy:
    # Set Git info
    - git config --global user.email "36317094+Noderize-bot@users.noreply.github.com"
    - git config --global user.name "Noderize Bot"
    - echo "machine github.com login Noderize-bot password $GITHUB_TOKEN" > ~/.netrc
    deploy:
      provider: script
      skip_cleanup: true
      script: (cd docs/website && yarn && GIT_USER=Noderize-bot yarn publish-gh-pages)
      on:
        all_branches: true
  # Deploy to npm on tags
  - stage: deploy
    env: DEPLOY=npm
    script: skip
    before_deploy:
    # Publish using $NPM_TOKEN
    - npm i -g ci-publish
    deploy:
      provider: script
      skip_cleanup: true
      script: (cd packages/scripts && ci-publish) && (cd packages/runtime && ci-publish) && (cd packages/create && ci-publish)
      on:
        tags: true